# Generated by Django 5.2 on 2026-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_type', models.CharField(choices=[('NONE', 'None'), ('TOT', 'TOT 4%'), ('VAT', 'VAT 16%')], default='NONE', max_length=10)),
                ('default_validity_period_days', models.PositiveIntegerField(default=30)),
                ('default_prepared_by_name', models.CharField(blank=True, max_length=120)),
                ('default_currency', models.CharField(default='ZMW', max_length=20)),
                ('letterhead', models.FileField(blank=True, upload_to='settings/letterheads/')),
                ('signature', models.FileField(blank=True, upload_to='settings/signatures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
