# Generated by Django 5.2 on 2026-07-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=120)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SATISFIED', 'Satisfied'), ('NEEDS_ADMIN', 'Needs admin clarification'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'TenderAI assistant'), ('ADMIN', 'Admin')], max_length=10)),
                ('message', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
