# Generated by Django 5.2 on 2026-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_supportchatsession_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_access_until',
            field=models.DateTimeField(blank=True, help_text='Leave blank for limited access unless the user is Pro.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro users can use TenderAI on multiple devices at the same time.'),
        ),
    ]
