# Generated by Django 5.2 on 2026-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_active_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of full-access days granted by admin. Use 0 for limited access.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
