# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, upload_to='analysis_uploads/%Y/%m/')),
                ('status', models.CharField(default='PLACEHOLDER_COMPLETE', max_length=40)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
