# Generated by Django 5.2 on 2026-06-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('tenders', '0004_zppascrapelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='solicitation_documents/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('analysis_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitation_documents', to='tenders.tender')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
