# Generated by Django 5.2 on 2026-06-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_solicitationdocument'),
        ('tenders', '0004_zppascrapelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitation_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='ai_engine.solicitationdocument')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
