# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('tender_number', models.CharField(blank=True, max_length=120)),
                ('procuring_entity', models.CharField(max_length=180)),
                ('source', models.CharField(choices=[('ZPPA', 'ZPPA'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('submission_method', models.CharField(blank=True, max_length=180)),
                ('bid_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('participation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('tender_document', models.FileField(blank=True, upload_to='tender_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('PREPARING_BID', 'Preparing Bid'), ('SUBMITTED', 'Submitted'), ('LOST', 'Lost'), ('WON', 'Won')], default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('imported_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='companies.businesscategory')),
            ],
            options={
                'ordering': ['closing_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TenderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('ELIGIBILITY', 'Eligibility'), ('MANDATORY_DOCUMENT', 'Mandatory Document'), ('BID_SECURITY', 'Bid Security'), ('SITE_VISIT', 'Site Visit'), ('EVALUATION', 'Evaluation Criteria'), ('REQUIRED_FORM', 'Required Form'), ('EXPERIENCE', 'Similar Experience'), ('CERTIFICATE', 'Required Certificate'), ('OTHER', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tenders.tender')),
            ],
            options={
                'ordering': ['tender', 'requirement_type'],
            },
        ),
        migrations.CreateModel(
            name='TenderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('missing_documents', models.TextField(blank=True)),
                ('expired_documents', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_matches', to='companies.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tenders.tender')),
            ],
            options={
                'ordering': ['-score', 'company__name'],
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
