# Generated by Django 5.2 on 2026-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='closing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tender',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='zppa_resource_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
