# Generated by Django 5.2 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_closing_at_tender_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='zppa_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
