# Generated by Django 5.2 on 2026-07-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_bidtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidtask',
            options={'ordering': ['sort_order', 'status', 'due_date', 'title']},
        ),
    ]
