# Generated by Django 5.2 on 2026-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_alter_bidtask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='clarification_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='itb_11_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_address',
            field=models.TextField(blank=True),
        ),
    ]
