# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('quotations', '0001_initial'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_cover_letter', models.BooleanField(default=True)),
                ('include_checklist', models.BooleanField(default=True)),
                ('include_company_profile', models.BooleanField(default=True)),
                ('include_price_schedule', models.BooleanField(default=True)),
                ('generated_docx', models.FileField(blank=True, upload_to='bid_packs/docx/%Y/%m/')),
                ('generated_pdf', models.FileField(blank=True, upload_to='bid_packs/pdf/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_packs', to='companies.company')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_packs', to='quotations.quotation')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_packs', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
