# Generated by Django 5.2 on 2026-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpack',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
