# Generated by Django 5.2 on 2026-07-03 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_generator', '0002_bidpack_generated_at'),
        ('documents', '0003_alter_companydocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope', models.CharField(blank=True, max_length=120)),
                ('requirement', models.CharField(max_length=240)),
                ('expected_response', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('mandatory', models.BooleanField(default=True)),
                ('generated_pdf', models.FileField(blank=True, upload_to='bid_documents/pdf/%Y/%m/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('bid_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_documents', to='bid_generator.bidpack')),
                ('matched_company_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bid_documents', to='documents.companydocument')),
            ],
            options={
                'ordering': ['order', 'envelope', 'requirement'],
                'unique_together': {('bid_pack', 'order', 'requirement')},
            },
        ),
    ]
