# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PACRA', 'PACRA'), ('ZRA_TAX_CLEARANCE', 'ZRA Tax Clearance'), ('TPIN_CERTIFICATE', 'TPIN Certificate'), ('NAPSA', 'NAPSA'), ('WORKERS_COMPENSATION', 'Workers Compensation'), ('NCC', 'NCC'), ('ZPPA_REGISTRATION', 'ZPPA Registration'), ('BANK_CONFIRMATION', 'Bank Confirmation Letter'), ('PAST_CONTRACT', 'Past Contract'), ('COMPANY_PROFILE', 'Company Profile'), ('OTHER', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='company_documents/%Y/%m/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'document_type', '-expiry_date'],
            },
        ),
    ]
