# Generated by Django 5.2 on 2026-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_companydocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='document_type',
            field=models.CharField(choices=[('PACRA', 'PACRA'), ('ZRA_TAX_CLEARANCE', 'ZRA Tax Clearance'), ('TPIN_CERTIFICATE', 'TPIN Certificate'), ('NAPSA', 'NAPSA'), ('WORKERS_COMPENSATION', 'Workers Compensation'), ('NCC', 'NCC'), ('NCC_B', 'NCC B'), ('NCC_R', 'NCC R'), ('NCC_E', 'NCC E'), ('ERB', 'ERB Registration / Licence'), ('EIZ_CERTIFICATE', 'EIZ Certificate'), ('ZPPA_REGISTRATION', 'ZPPA Registration'), ('BANK_CONFIRMATION', 'Bank Confirmation Letter'), ('PAST_CONTRACT', 'Past Contract'), ('COMPANY_PROFILE', 'Company Profile'), ('OTHER', 'Other')], max_length=40),
        ),
    ]
