# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'business categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('tpin', models.CharField(blank=True, max_length=50, verbose_name='TPIN')),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('profile_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_categories', models.ManyToManyField(blank=True, related_name='companies', to='companies.businesscategory')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=160)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(max_length=160)),
                ('account_number', models.CharField(max_length=80)),
                ('swift_code', models.CharField(blank=True, max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('national_id', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PacraDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporation_number', models.CharField(blank=True, max_length=80)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(blank=True, max_length=80)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacra_detail', to='companies.company')),
            ],
        ),
    ]
