# Generated by Django 5.2 on 2026-07-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0003_organization_supportchatsession_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_company_name_per_organization'),
        ),
    ]
