# Generated by Django 5.2 on 2026-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_seed_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='letterhead_pdf',
            field=models.FileField(blank=True, upload_to='company_letterheads/%Y/%m/'),
        ),
    ]
