# Generated by Django 5.2 on 2026-07-02 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('facebook_url', models.URLField(max_length=500, unique=True)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['province', 'district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('pages_checked', models.PositiveIntegerField(default=0)),
                ('posts_found', models.PositiveIntegerField(default=0)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('posts_updated', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('post_url', models.URLField(max_length=700, unique=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('CDF', 'CDF'), ('Tender', 'Tender'), ('RFQ', 'RFQ'), ('Procurement', 'Procurement'), ('Grant', 'Grant'), ('Bursary', 'Bursary'), ('Other', 'Other')], default='Other', max_length=20)),
                ('detected_deadline', models.DateField(blank=True, null=True)),
                ('attachment_url', models.URLField(blank=True, max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='council_opportunities.councilpage')),
            ],
            options={
                'ordering': ['-date_posted', '-date_scraped', '-id'],
                'indexes': [models.Index(fields=['category'], name='council_opp_categor_cb537c_idx'), models.Index(fields=['detected_deadline'], name='council_opp_detecte_f10a42_idx'), models.Index(fields=['date_posted'], name='council_opp_date_po_e10d48_idx')],
            },
        ),
    ]
