# Generated by Django 5.2 on 2026-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilpage',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
