# Generated by Django 5.2 on 2026-06-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_tpin', models.CharField(blank=True, max_length=50, verbose_name='Customer TPIN')),
                ('customer_address', models.TextField(blank=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('date', models.DateField()),
                ('tax_type', models.CharField(choices=[('NONE', 'None'), ('TOT', 'TOT 4%'), ('VAT', 'VAT 16%')], default='NONE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_tpin', models.CharField(blank=True, max_length=50, verbose_name='Customer TPIN')),
                ('customer_address', models.TextField(blank=True)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('date', models.DateField()),
                ('tax_type', models.CharField(choices=[('NONE', 'None'), ('TOT', 'TOT 4%'), ('VAT', 'VAT 16%')], default='NONE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_period_days', models.PositiveIntegerField(default=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
